# Generated by Django 5.0.6 on 2025-06-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_alter_fichaacogida_fecha_recepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_amistades',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_centro_madres',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_cesfam',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_club_adultos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_club_deportivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_conyuge',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_cosam',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_establecimiento',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_familiares',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_junta_vecinos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_laborales',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_municipalidad',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_ong',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_otro_salud',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_otros_comunitarios',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redesapoyo',
            name='red_otros_personales',
            field=models.TextField(blank=True),
        ),
    ]
