# Generated by Django 5.0.6 on 2025-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_alter_redesapoyo_red_amistades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaccion',
            name='cordinadora_gloria',
            field=models.BooleanField(default=False),
        ),
    ]
