# Generated by Django 5.2.1 on 2025-06-05 17:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_planaccion_cordinadora_gloria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaacogida',
            name='contencion_inicial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichaacogida',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaacogida',
            name='ingreso_efectivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichaacogida',
            name='profesionales_contacto_1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
