# Generated by Django 5.2.1 on 2025-06-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_fichaacogida_contencion_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='descripcion_dificultad',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='dificultades_denuncia',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='dificultades',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='dificultades_otra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='lugar_denuncia_otro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='medida_cautelar_detalle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
