# Generated by Django 5.2.1 on 2025-06-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_remove_denuncia_descripcion_dificultad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoingreso',
            name='motivo_otro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='motivoingreso',
            name='motivo_ingreso',
            field=models.CharField(choices=[('VIF_MUJER', 'Violencia Intrafamiliar contra la mujer'), ('VIF_HOMBRE', 'Violencia Intrafamiliar contra el hombre'), ('VIF_NNA', 'Violencia Intrafamiliar contra niño/niña'), ('VIF_AM', 'Violencia Intrafamiliar contra adulto mayor'), ('VULNERACION_NNA', 'Vulneración de derechos a NNA'), ('FEMICIDIO', 'Femicidio'), ('PARRICIDIO', 'Parricidio'), ('SECUESTRO', 'Secuestro / Intento Secuestro'), ('DELITO_SEXUAL', 'Delito Sexual'), ('ROBO', 'Robo'), ('SUSTRACCION', 'Sustracción de Menores'), ('HOMICIDIO', 'Homicidio / Cuasidelito de Homicidio'), ('BALACERAS', 'Balas Locas / Balaceras'), ('LESIONES', 'Lesiones'), ('ODIO', 'Crímenes de Odio'), ('AMENAZAS', 'Amenazas'), ('DAÑOS', 'Daños'), ('FALLECIMIENTO', 'Fallecimientos'), ('OTROS', 'Otro')], max_length=50),
        ),
    ]
