# Generated by Django 5.2.1 on 2025-06-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0007_motivoingreso_motivo_otro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectospsicologicos',
            name='afectacion_psicologica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aspectospsicologicos',
            name='antecedentes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aspectospsicologicos',
            name='atencion_anio',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='aspectospsicologicos',
            name='atencion_lugar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aspectospsicologicos',
            name='atencion_salud_mental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspectospsicologicos',
            name='diagnostico',
            field=models.CharField(blank=True, choices=[('estado_animo', 'Trastornos del estado de ánimo (depresión, bipolaridad, distimia)'), ('ansiedad', 'Trastornos de ansiedad (ansiedad generalizada, crisis de pánico, fobias)'), ('psicoticos', 'Trastornos psicóticos (esquizofrenia, delirante, psicosis no especificada)'), ('personalidad', 'Trastornos de la personalidad (límite, antisocial, evitativa)'), ('consumo', 'Trastornos por consumo de sustancias (alcohol, drogas, psicotrópicos)'), ('neurodesarrollo', 'Trastornos del neurodesarrollo (autismo, TDAH, discapacidad intelectual leve)'), ('conducta_alimentaria', 'Trastornos de la conducta alimentaria (anorexia, bulimia, atracón)'), ('adaptativos', 'Trastornos adaptativos y reacción al estrés (estrés agudo, adaptativo, TEPT)'), ('somatomorfos', 'Trastornos somatomorfos y psicosomáticos (somatización, dolor crónico sin causa médica)'), ('disociativos', 'Trastornos disociativos (amnesia disociativa, despersonalización)'), ('no_especificado', 'Problemas de salud mental no especificados (malestar emocional, síntomas inespecíficos)'), ('otro', 'Otro (especifique)')], max_length=32),
        ),
        migrations.AddField(
            model_name='aspectospsicologicos',
            name='diagnostico_otro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aspectospsicologicos',
            name='internacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspectospsicologicos',
            name='internacion_anio',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='aspectospsicologicos',
            name='internacion_lugar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='registro_patrullaje',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='uav_legal_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='uav_legal_1_detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='uav_legal_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='uav_legal_2_detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='uav_legal_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planaccion',
            name='uav_legal_3_detalle',
            field=models.TextField(blank=True),
        ),
    ]
