# Generated by Django 5.2.1 on 2025-06-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0009_alter_denuncia_dificultades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='dificultades',
            field=models.CharField(blank=True, choices=[('mal_trato', 'Mal trato/trato inadecuado'), ('tiempo_espera', 'Tiempo de espera'), ('no_llegaron', 'No llegaron a llamado'), ('otra', 'Otra')], max_length=30, null=True),
        ),
    ]
