# Generated by Django 5.2.1 on 2025-06-06 15:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0010_alter_denuncia_dificultades'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencion',
            name='cumplimiento_objetivo',
            field=models.CharField(blank=True, choices=[('Total', 'Total'), ('Parcial', 'Parcial'), ('No cumple', 'No cumple')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='objetivos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='responsables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='personaatendida',
            name='genero',
            field=models.CharField(blank=True, choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino'), ('TRANSMASCULINO', 'Transmasculino'), ('TRANSFEMENINA', 'Transfemenina'), ('NO_BINARIO', 'No Binario'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
