# Generated by Django 5.2.1 on 2025-06-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0011_intervencion_cumplimiento_objetivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervencion',
            name='cumplimiento_objetivo',
        ),
    ]
