# Generated by Django 5.2.1 on 2025-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0012_remove_intervencion_cumplimiento_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaatendida',
            name='rango_etareo',
            field=models.CharField(blank=True, choices=[('0-14', '0-14 años'), ('15-17', '15-17 años'), ('18-30', '18-30 años'), ('31-40', '31-40 años'), ('41-59', '41-59 años'), ('60+', '60 años o más')], max_length=10),
        ),
    ]
