# Generated by Django 5.2.1 on 2025-06-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0013_alter_personaatendida_rango_etareo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaatendida',
            name='genero_otro',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
