# Generated by Django 5.2.1 on 2025-06-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0014_personaatendida_genero_otro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaatendida',
            name='prevision',
            field=models.CharField(blank=True, choices=[('FONASA', 'FONASA'), ('ISAPRE', 'ISAPRE'), ('CAPREDENA', 'CAPREDENA'), ('NINGUNA', 'Ninguna')], max_length=20),
        ),
    ]
