# Generated by Django 5.2.1 on 2025-06-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0015_alter_personaatendida_prevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaatendida',
            name='cesfam_otro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personaatendida',
            name='cesfam',
            field=models.CharField(blank=True, choices=[('', '---------'), ('CESFAM Maipú (Pajaritos)', 'CESFAM Maipú (Pajaritos)'), ('CESFAM Dra. Ana María Juricic', 'CESFAM Dra. Ana María Juricic'), ('CESFAM Dr. Eduardo Ahués', 'CESFAM Dr. Eduardo Ahués'), ('CESFAM Dr. Carlos Godoy', 'CESFAM Dr. Carlos Godoy'), ('CESFAM Dr. Iván Insunza', 'CESFAM Dr. Iván Insunza'), ('CESFAM Clotario Blest', 'CESFAM Clotario Blest'), ('CESFAM Presidenta Michelle Bachelet', 'CESFAM Presidenta Michelle Bachelet'), ('CESFAM Dr. Luis Ferrada', 'CESFAM Dr. Luis Ferrada'), ('CESFAM Dr. Salvador Allende (El Abrazo)', 'CESFAM Dr. Salvador Allende (El Abrazo)'), ('OTRO', 'Otro (especifique)')], max_length=100),
        ),
    ]
