# Generated by Django 5.2.1 on 2025-06-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0016_personaatendida_cesfam_otro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencion',
            name='tipo_intervencion',
            field=models.CharField(choices=[('Psicológica', 'Psicológica'), ('Social', 'Social'), ('Psicosocial', 'Psicosocial'), ('Vinculación con red', 'Vinculación con red'), ('Taller de duelo', 'Taller de duelo'), ('Otra', 'Otra')], max_length=50),
        ),
    ]
