# Generated by Django 5.2.1 on 2025-06-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0017_alter_intervencion_tipo_intervencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planaccion',
            name='derivacion_cavd_juridica',
        ),
        migrations.RemoveField(
            model_name='planaccion',
            name='derivacion_cavd_psicologica',
        ),
        migrations.RemoveField(
            model_name='planaccion',
            name='derivacion_cesfam_salud_general',
        ),
        migrations.RemoveField(
            model_name='planaccion',
            name='derivacion_cesfam_salud_mental',
        ),
    ]
