# Generated by Django 5.2.1 on 2025-06-12 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0018_remove_planaccion_derivacion_cavd_juridica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAVD', 'Programa Atención a Víctimas (CAVD)'), ('URAVIT', 'URAVIT Fiscalía'), ('CDM_CAI', 'CDM-CAI'), ('SALUD', 'Salud'), ('OFAM', 'OFAM'), ('DIDECO', 'DIDECO'), ('GESTION_TERRITORIAL', 'Gestión Territorial'), ('CAPS_UDLA', 'CAPS UDLA'), ('OLN', 'OLN'), ('OTRO', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('es_vinculacion', models.BooleanField(default=False, help_text='¿Es derivación o solo vinculación?')),
                ('fecha_derivacion', models.DateField(blank=True, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('ingresa', models.BooleanField(default=False, help_text='¿La persona ingresó al servicio derivado?')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('conmocion_publica', models.BooleanField(default=False)),
                ('dispositivo_salud', models.CharField(blank=True, max_length=100)),
                ('institucion_otro', models.CharField(blank=True, max_length=200)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='fichas.fichaacogida')),
            ],
        ),
    ]
