# Generated by Django 5.2.1 on 2025-06-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0019_derivacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivacion',
            name='es_vinculacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='derivacion',
            name='ingresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='derivacion',
            name='tipo',
            field=models.CharField(choices=[('CAVD', 'Programa Atención a Víctimas (CAVD)'), ('URAVIT', 'URAVIT Fiscalía'), ('CDM_CAI', 'CDM-CAI'), ('SALUD', 'Salud'), ('OFAM', 'OFAM'), ('DIDECO', 'DIDECO'), ('GESTION_TERRITORIAL', 'Gestión Territorial'), ('CAPS_UDLA', 'CAPS UDLA'), ('OLN', 'OLN'), ('OTRO', 'Otro')], max_length=100),
        ),
    ]
