# Generated by Django 5.2.1 on 2025-06-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0020_alter_derivacion_es_vinculacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivacion',
            name='tipo',
            field=models.CharField(choices=[('CAVD', 'Programa Atención a Víctimas (CAVD)'), ('URAVIT', 'URAVIT Fiscalía'), ('CDM_CAI', 'CDM-CAI'), ('SALUD', 'Salud'), ('OFAM', 'OFAM'), ('DIDECO', 'DIDECO'), ('GESTION_TERRITORIAL', 'Gestión Territorial'), ('CAPS_UDLA', 'CAPS UDLA'), ('OLN', 'OLN'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.CreateModel(
            name='DerivacionCapsUdla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_caps_udla', models.TextField(blank=True)),
                ('fecha_derivacion_caps_udla', models.DateField(blank=True, null=True)),
                ('es_vinculacion_caps_udla', models.BooleanField(default=False)),
                ('fecha_respuesta_caps_udla', models.DateField(blank=True, null=True)),
                ('ingresa_caps_udla', models.BooleanField(default=False)),
                ('fecha_ingreso_caps_udla', models.DateField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivacion_caps_udla', to='fichas.fichaacogida')),
            ],
        ),
        migrations.CreateModel(
            name='DerivacionCavd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_cavd', models.TextField(blank=True)),
                ('fecha_derivacion_cavd', models.DateField(blank=True, null=True)),
                ('es_vinculacion_cavd', models.BooleanField(default=False)),
                ('fecha_respuesta_cavd', models.DateField(blank=True, null=True)),
                ('ingresa_cavd', models.BooleanField(default=False)),
                ('fecha_ingreso_cavd', models.DateField(blank=True, null=True)),
                ('es_conmocion_publica_cavd', models.BooleanField(default=False)),
                ('fecha_vinculacion_conmocion_cavd', models.DateField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivacion_cavd', to='fichas.fichaacogida')),
            ],
        ),
        migrations.CreateModel(
            name='DerivacionCdmCai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_cdm_cai', models.TextField(blank=True)),
                ('fecha_derivacion_cdm_cai', models.DateField(blank=True, null=True)),
                ('es_vinculacion_cdm_cai', models.BooleanField(default=False)),
                ('fecha_respuesta_cdm_cai', models.DateField(blank=True, null=True)),
                ('ingresa_cdm_cai', models.BooleanField(default=False)),
                ('fecha_ingreso_cdm_cai', models.DateField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivacion_cdm_cai', to='fichas.fichaacogida')),
            ],
        ),
        migrations.CreateModel(
            name='DerivacionDideco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_dideco', models.TextField(blank=True)),
                ('fecha_derivacion_dideco', models.DateField(blank=True, null=True)),
                ('es_vinculacion_dideco', models.BooleanField(default=False)),
                ('fecha_respuesta_dideco', models.DateField(blank=True, null=True)),
                ('ingresa_dideco', models.BooleanField(default=False)),
                ('fecha_ingreso_dideco', models.DateField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivacion_dideco', to='fichas.fichaacogida')),
            ],
        ),
        migrations.CreateModel(
            name='DerivacionGestionTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_gestion_territorial', models.TextField(blank=True)),
                ('fecha_derivacion_gestion_territorial', models.DateField(blank=True, null=True)),
                ('es_vinculacion_gestion_territorial', models.BooleanField(default=False)),
                ('fecha_respuesta_gestion_territorial', models.DateField(blank=True, null=True)),
                ('ingresa_gestion_territorial', models.BooleanField(default=False)),
                ('fecha_ingreso_gestion_territorial', models.DateField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivacion_gestion_territorial', to='fichas.fichaacogida')),
            ],
        ),
        migrations.CreateModel(
            name='DerivacionOfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ofam', models.TextField(blank=True)),
                ('fecha_derivacion_ofam', models.DateField(blank=True, null=True)),
                ('es_vinculacion_ofam', models.BooleanField(default=False)),
                ('fecha_respuesta_ofam', models.DateField(blank=True, null=True)),
                ('ingresa_ofam', models.BooleanField(default=False)),
                ('fecha_ingreso_ofam', models.DateField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivacion_ofam', to='fichas.fichaacogida')),
            ],
        ),
        migrations.CreateModel(
            name='DerivacionOln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_oln', models.TextField(blank=True)),
                ('fecha_derivacion_oln', models.DateField(blank=True, null=True)),
                ('es_vinculacion_oln', models.BooleanField(default=False)),
                ('fecha_respuesta_oln', models.DateField(blank=True, null=True)),
                ('ingresa_oln', models.BooleanField(default=False)),
                ('fecha_ingreso_oln', models.DateField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivacion_oln', to='fichas.fichaacogida')),
            ],
        ),
        migrations.CreateModel(
            name='DerivacionOtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_otro', models.CharField(blank=True, max_length=200)),
                ('descripcion_otro', models.TextField(blank=True)),
                ('fecha_derivacion_otro', models.DateField(blank=True, null=True)),
                ('es_vinculacion_otro', models.BooleanField(default=False)),
                ('fecha_respuesta_otro', models.DateField(blank=True, null=True)),
                ('ingresa_otro', models.BooleanField(default=False)),
                ('fecha_ingreso_otro', models.DateField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivacion_otro', to='fichas.fichaacogida')),
            ],
        ),
        migrations.CreateModel(
            name='DerivacionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_salud', models.CharField(blank=True, choices=[('', '---------'), ('CESFAM Maipú (Pajaritos)', 'CESFAM Maipú (Pajaritos)'), ('CESFAM Dra. Ana María Juricic', 'CESFAM Dra. Ana María Juricic'), ('CESFAM Dr. Eduardo Ahués', 'CESFAM Dr. Eduardo Ahués'), ('CESFAM Dr. Carlos Godoy', 'CESFAM Dr. Carlos Godoy'), ('CESFAM Dr. Iván Insunza', 'CESFAM Dr. Iván Insunza'), ('CESFAM Clotario Blest', 'CESFAM Clotario Blest'), ('CESFAM Presidenta Michelle Bachelet', 'CESFAM Presidenta Michelle Bachelet'), ('CESFAM Dr. Luis Ferrada', 'CESFAM Dr. Luis Ferrada'), ('CESFAM Dr. Salvador Allende (El Abrazo)', 'CESFAM Dr. Salvador Allende (El Abrazo)'), ('OTRO', 'Otro (especifique)')], max_length=100)),
                ('fecha_derivacion_salud', models.DateField(blank=True, null=True)),
                ('es_vinculacion_salud', models.BooleanField(default=False)),
                ('fecha_respuesta_salud', models.DateField(blank=True, null=True)),
                ('ingresa_salud', models.BooleanField(default=False)),
                ('fecha_ingreso_salud', models.DateField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivacion_salud', to='fichas.fichaacogida')),
            ],
        ),
        migrations.CreateModel(
            name='DerivacionUravit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_uravit', models.TextField(blank=True)),
                ('fecha_derivacion_uravit', models.DateField(blank=True, null=True)),
                ('es_vinculacion_uravit', models.BooleanField(default=False)),
                ('fecha_respuesta_uravit', models.DateField(blank=True, null=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derivacion_uravit', to='fichas.fichaacogida')),
            ],
        ),
    ]
