# Generated by Django 5.0.6 on 2025-06-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0022_derivacionsalud_dispositivo_salud_otro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaacogida',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20),
        ),
    ]
