# Generated by Django 5.2.1 on 2025-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0024_fichachangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichachangelog',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('EDITADO', 'Editado'), ('ELIMINADO', 'Eliminado')], default='EDITADO', max_length=16),
        ),
    ]
