# Generated by Django 5.2.1 on 2025-06-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0025_fichachangelog_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectospsicologicos',
            name='limitacion_vida_cotidiana',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
