# Generated by Django 5.2.1 on 2025-06-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0026_alter_aspectospsicologicos_limitacion_vida_cotidiana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectospsicologicos',
            name='diagnostico',
            field=models.CharField(blank=True, choices=[('estado_animo', 'Trastornos del estado de ánimo'), ('ansiedad', 'Trastornos de ansiedad'), ('psicoticos', 'Trastornos psicóticos'), ('personalidad', 'Trastornos de la personalidad'), ('consumo', 'Trastornos por consumo de sustancias'), ('neurodesarrollo', 'Trastornos del neurodesarrollo'), ('conducta_alimentaria', 'Trastornos de la conducta alimentaria'), ('adaptativos', 'Trastornos adaptativos y reacción al estrés'), ('somatomorfos', 'Trastornos somatomorfos y psicosomáticos'), ('disociativos', 'Trastornos disociativos'), ('no_especificado', 'Problemas de salud mental no especificados'), ('otro', 'Otro (especifique)')], max_length=32),
        ),
    ]
