# Generated by Django 5.0.6 on 2025-04-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('PROFESIONAL', 'Profesional UAV'), ('COORDINACION', 'Coordinación UAV'), ('ADMINISTRADOR', 'Administrador del Sistema')], default='PROFESIONAL', max_length=20, verbose_name='Rol del usuario'),
        ),
    ]
